name: Build geoIP rules
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 12 * *"

jobs:
  build-geo:
    name: Build geoip.dat
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          mkdir geoip rule-set-geoip
        shell: bash


      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          path: code

      - name: Checkout v2fly/geoip
        uses: actions/checkout@v4
        with:
          repository: v2fly/geoip
          path: code/v2fly-geoip

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: code/v2fly-geoip/go.mod
          cache-dependency-path: code/v2fly-geoip/go.sum

      - name: Build geoip.dat file
        run: |
          cd code/v2fly-geoip || exit 1
          cp ../config/v2fly-geoip.json ./config.json
          go run ./ 
          cd ../ && rm -rf v2fly-geoip
          cd ../


      - name: Checkout MYffffff/sing-geoip
        uses: actions/checkout@v4
        with:
          repository: MYffffff/sing-geoip
          path: code/myfff-sing

      - name: Update Go deps
        run: |
            cd code/myfff-sing
            go mod tidy
            cd ../../

      - name: Build sing-geo
        run: |
          cd code/myfff-sing || exit 1
          go run ./ --inputfile ../data/Country.mmdb --inputdir ../data/ips --geofile ../../geoip/geoip.db --srsdir ../../rule-set-geoip
          cd ../../ && rm -rf myfff-sing


      - name: Generate Zip, XZ, sha256
        run: |
          cd geoip 
          sha256sum geoip.dat > geoip.dat.sha256sum
          sha256sum geoip.db > geoip.db.sha256sum

          zip -9 geoip.dat.zip geoip.dat
          sha256sum geoip.dat.zip > geoip.dat.zip.sha256sum
          zip -9 geoip.db.zip geoip.db
          sha256sum geoip.db.zip > geoip.db.zip.sha256sum

          xz -z -9 -k geoip.dat
          sha256sum geoip.dat.xz > geoip.dat.xz.sha256sum
          xz -z -9 -k geoip.db
          sha256sum geoip.db.xz > geoip.db.xz.sha256sum
          cd ../


      - name: Git push assets to "geosite" branch
        run: |
          cd geoip
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@noreply.github.com"
          git branch -M geoip
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin geoip
          cd ../

      - name: Git push assets to "sing-site" branch
        run: |
          cd rule-set-geoip
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@noreply.github.com"
          git branch -M rule-set-geoip
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin rule-set-geoip
          cd ../