name: Build geoSite rules
on:
  workflow_dispatch:
  schedule:
    - cron: "40 14 * * 5"

jobs:
  build:
    name: Build geoSite rules
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          mkdir geosite rule-set-geosite
        shell: bash


      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          path: code

      - name: Checkout MYffffff/domain-list-ru
        uses: actions/checkout@v4
        with:
          repository: MYffffff/domain-list-ru
          path: code/rcode

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: code/rcode/go.mod
          cache-dependency-path: code/rcode/go.sum
          
      - name: Build geo.dat
        run: |
          cd code/rcode || exit 1
          go run ./ --datapath ../data/domains --outputdir ../../geosite
          cd ../../ && rm -rf code


      - name: Checkout MYffffff/sing-geosite
        uses: actions/checkout@v4
        with:
          repository: MYffffff/sing-geosite
          path: rcode

      - name: Update Go deps
        run: |
          cd rcode || exit 1
          go mod tidy
          cd ../

      - name: Build geo.db
        run: |
          cd rcode || exit 1
          go run ./ --geofile ../geosite/geosite.db --srsdir ../rule-set-geosite --inputfile ../geosite/geosite.dat
          cd ../ && rm -rf rcode

      - name: Generate Zip, XZ, sha256
        run: |
          cd geosite
          sha256sum geosite.db > geosite.db.sha256sum
          sha256sum geosite.dat > geosite.dat.sha256sum

          zip -9 geosite.db.zip geosite.db
          sha256sum geosite.db.zip > geosite.db.zip.sha256sum
          zip -9 geosite.dat.zip geosite.dat
          sha256sum geosite.dat.zip > geosite.dat.zip.sha256sum

          xz -z -9 -k geosite.db
          sha256sum geosite.db.xz > geosite.db.xz.sha256sum
          xz -z -9 -k geosite.dat
          sha256sum geosite.dat.xz > geosite.dat.xz.sha256sum
          cd ../


      - name: Git push assets to "geosite" branch
        run: |
          cd geosite
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@noreply.github.com"
          git branch -M geosite
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin geosite
          cd ../

      - name: Git push assets to "rule-set-geosite" branch
        run: |
          cd rule-set-geosite
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@noreply.github.com"
          git branch -M rule-set-geosite
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin rule-set-geosite
          cd ../
