name: Release databases

on:
  workflow_run:
    workflows: ["Build geoIP rules", "Build geoSite rules"]
    types:
      - completed
    branches:
      - geoip
      - geosite
      - rule-set-geosite
      - rule-set-geoip
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        shell: bash

      - name: Checkout geoip branch
        uses: actions/checkout@v4
        with:
          ref: geoip
          path: geoip

      - name: Checkout geosite branch
        uses: actions/checkout@v4
        with:
          ref: geosite
          path: geosite

      - name: Checkout rule-set-geosite
        uses: actions/checkout@v4
        with:
          ref: rule-set-geosite
          path: rule-set-geosite

      - name: Checkout rule-set-geoip
        uses: actions/checkout@v4
        with:
          ref: rule-set-geoip
          path: rule-set-geoip

      - name: Make sing-rules xz archives
        run: |
          tar -cJvf rule-set-geosite.tar.xz rule-set-geosite/geosite-*
          tar -cJvf rule-set-geoip.tar.xz rule-set-geoip/geoip-*
          sha256sum rule-set-geosite.tar.xz > rule-set-geosite.tar.xz.sha256sum
          sha256sum rule-set-geoip.tar.xz > rule-set-geoip.tar.xz.sha256sum
          rm -r rule-set-geosite rule-set-geoip

      - name: Prepare packages to release
        run: |
          cp geoip/geoip.db ./
          cp geoip/geoip.db.sha256sum ./
          cp geoip/geoip.db.xz ./
          cp geoip/geoip.db.xz.sha256sum ./

          cp geoip/geoip.dat ./
          cp geoip/geoip.dat.sha256sum ./
          cp geoip/geoip.dat.xz ./
          cp geoip/geoip.dat.xz.sha256sum ./
          
          cp geosite/geosite.db ./
          cp geosite/geosite.db.sha256sum ./
          cp geosite/geosite.db.xz ./
          cp geosite/geosite.db.xz.sha256sum ./

          cp geosite/geosite.dat ./
          cp geosite/geosite.dat.sha256sum ./
          cp geosite/geosite.dat.xz ./
          cp geosite/geosite.dat.xz.sha256sum ./

          rm -r geosite geoip


      - uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
            keep_latest: 3
            keep_min_download_counts: 1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Git push assets to "release" branch
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Release and upload assets
        run: |
          gh release create ${{ env.TAG_NAME }} --generate-notes --latest --title ${{ env.RELEASE_NAME }} ./rule-set-geosite* ./rule-set-geoip* ./geosite* ./geoip*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}